var music1 = new Audio();
music1.src = "key01.mp3";
function Audio1() {
    music15.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music1.play();
}
var music2 = new Audio();
music2.src = " key02.mp3";
function Audio2() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music15.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music2.play();
}
var music3 = new Audio();
music3.src = " key03.mp3";
function Audio3() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music15.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music3.play();
}
var music4 = new Audio();
music4.src = " key04.mp3";
function Audio4() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music15.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music4.play();
}
var music5 = new Audio();
music5.src = " key05.mp3";
function Audio5() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music15.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music5.play();
}
var music6 = new Audio();
music6.src = " key06.mp3";
function Audio6() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music15.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music6.play();
}
var music7 = new Audio();
music7.src = " key07.mp3";
function Audio7() {
    music12.pause();
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music15.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music7.play();
}
var music8 = new Audio();
music8.src = " key08.mp3";
function Audio8() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music15.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music8.play();
}
var music9 = new Audio();
music9.src = " key09.mp3";
function Audio9() {
    music1.pause();
    music11.pause();
    music10.pause();
    music15.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music9.play();
}
var music10 = new Audio();
music10.src = "key10.mp3";
function Audio10() {
    music1.pause();
    music11.pause();
    music15.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music10.play();
}
var music11 = new Audio();
music11.src = "key11.mp3";
function Audio11() {
    music1.pause();
    music15.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music11.play();
}
var music12 = new Audio();
music12.src = "key12.mp3";
function Audio12() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music15.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music12.play();
}
var music13 = new Audio();
music13.src = " key13.mp3";
function Audio13() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music15.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music13.play();
}
var music14 = new Audio();
music14.src = "key14.mp3";
function Audio14() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music24.pause();
    music15.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music14.play();
}
var music15 = new Audio();
music15.src = "key15.mp3";
function Audio15() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music24.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music15.play();
}
var music16 = new Audio();
music16.src = "key16.mp3";
function Audio16() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music15.pause();
    music24.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music16.play();
}
var music17 = new Audio();
music17.src = "key17.mp3";
function Audio17() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music15.pause();
    music16.pause();
    music24.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music17.play();
}
var music18 = new Audio();
music18.src = "key18.mp3";
function Audio18() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music15.pause();
    music16.pause();
    music17.pause();
    music24.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music18.play();
}
var music19 = new Audio();
music19.src = "key19.mp3";
function Audio19() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music15.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music24.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music19.play();
}
var music20 = new Audio();
music20.src = "key20.mp3";
function Audio20() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music15.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music24.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music20.play();
}
var music21 = new Audio();
music21.src = "key21.mp3";
function Audio21() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music15.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music21.play();
}
var music22 = new Audio();
music22.src = "key22.mp3";
function Audio22() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music15.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music24.pause();
    music23.pause();
    music22.play();
}
var music23 = new Audio();
music23.src = "key23.mp3";
function Audio23() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music15.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music24.pause();
    music23.play();
}
var music24 = new Audio();
music24.src = "key24.mp3";
function Audio24() {
    music1.pause();
    music11.pause();
    music10.pause();
    music9.pause();
    music8.pause();
    music7.pause();
    music6.pause();
    music5.pause();
    music4.pause();
    music3.pause();
    music2.pause();
    music12.pause();
    music13.pause();
    music14.pause();
    music15.pause();
    music16.pause();
    music17.pause();
    music18.pause();
    music19.pause();
    music20.pause();
    music21.pause();
    music22.pause();
    music23.pause();
    music24.play();
}
